### ISSUE TITLE
Appropriate attribution and License

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/skeletor#17]
- [ ] Add a section to the README explaining 
  - [ ] what it shares in common with Skeleton 
  - [ ] how this diverges from Skelton 

- [ ] Give appropriate attribution to Skelton in the LICENSE

**Comment by winkerVSbecks** [comment]
@bertrandk you working on this? I was about to update the README with how to use skeletor and skeletor vs skeleton

**Comment by bertrandk** [comment]
@winkerVSbecks if you have time, please have at it.

**Comment by winkerVSbecks** [comment]
@bertrandk I can take care of this. Thanks
