### ISSUE TITLE
Fix comments to use `//` style only

### ISSUE THREAD

**Issue by winkerVSbecks** [rangle/skeletor#30]
This would require and update to the `scss-lint.yml` file too. CSS technically doesn't support the `//` syntax: https://developer.mozilla.org/en-US/docs/Web/CSS/Comments

**Comment by winkerVSbecks** [comment]
@bertrandk @neilff @lustandfury @SethDavenport @claudiareinoza @abmohan @AbdellaToronto @danielschifano 

Question about comments style... scss-Lint enforces `//` because those comments don't show up in the final CSS. `/* */` comments do.  https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md#comment

I previously had a mix where the section headers were `/* */` and everything else `//`. But, linter doesn't allow us to enforce this style. How does everyone feel about enforcing `//` style comments only? for example:

```css

// Section Name
// ––––––––––––––––––––––––––––––––––––––––––––––––––

// inline comment

```

**Comment by neilff** [comment]
Interesting, `//` is fine, we should probably align on some commenting structures, even if they are the two you've posted above... or else we will start seeing different styles of section headers / inline / long comments.

**Comment by winkerVSbecks** [comment]
Yes that too. This is what I propose:

```
// File Header
// ––––––––––––––––––––––––––––––––––––––––––––––––––


// File Header
//
// The long description is ideal for more detailed
// explanations and documentation. It can include
// example HTML, URLs, or any other information
// that is deemed necessary or useful.
–––––––––––––––––––––––––––––––––––––––––––––––––– 


// Basic comment
```

**Comment by neilff** [comment]
Looks good!

**Comment by bertrandk** [comment]
:+1:

**Comment by mattmischuk** [comment]
:+1:
