### ISSUE TITLE
`bower install` in README

### ISSUE THREAD

**Issue by bertrandk** [rangle/skeletor#9]
Is there a reason the README instructs to run a `bower install` after the `npm install`? We don't have plan for any bower dependencies do we?

**Comment by winkerVSbecks** [comment]
I don't think we're going to have bower dependencies for this. It goes against our goal of keeping it light.

**Comment by bertrandk** [comment]
I agree...thought normalize.css might be an exception.

**Comment by bertrandk** [comment]
I'll circle around to this when a do bower and npm packaging.

**Comment by winkerVSbecks** [comment]
yes, however I modified `normalize.css` slightly to follow the BEM syntax. I don't mind adding it through bower though.

**Comment by bertrandk** [comment]
Hum...I'm fine tracking upstream and keeping the forked version embedded. It's a reset after all...functional changes are rare. Will close after removing the reference.
